name: "npm publish"

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: publish
        run: npm publish
        working-directory: .
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}
